import type { Metadata } from 'next'
import { Karla, Nunito } from 'next/font/google'
import './globals.css'

const karla = Karla({
  variable: '--font-karla',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
})

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${karla.variable} ${nunito.variable} antialiased w-dvw px-28 py-10 bg-blue-100`}
      >
        {children}
      </body>
    </html>
  )
}
